#include <stdio.h>
#include "test.h"

int main()
{
    test_convertMMA();
    test_convertMMB();
    test_convertMMC();
    test_convertMMD();
    test_convertSMA();
    test_convertSMB();
    test_convertSMC();
    test_convertSMD();
    test_convertMA();
    test_convertMB();
    test_convertMC();
    test_convertMD();
    test_convertCA();
    test_convertCB();
    test_convertKA();
    test_convertKB();
    test_convertFA();
    test_convertFB();
    test_convertGRA();
    test_convertGRB();
    test_convertGRC();
    test_convertGRD();
    test_convertGRE();
    test_convertKRA();
    test_convertKRB();
    test_convertKRC();
    test_convertKRD();
    test_convertHWA();
    test_convertHWB();
    test_convertHWC();
    test_convertHWD();
    test_convertSECA();
    test_convertSECB();
    test_convertSECC();
    test_convertSECD();
    test_convertSECE();
    test_convertMINA();
    test_convertMINB();
    test_convertMINC();
    test_convertMIND();
    test_convertMINE();
    test_convertHOURA();
    test_convertHOURB();
    test_convertHOURC();
    test_convertHOURD();
    test_convertHOURE();
    test_convertMONTHA();
    test_convertMONTHB();
    test_convertMONTHC();
    test_convertMONTHD();
    test_convertMONTHE();
    test_convertYEARA();
    test_convertYEARB();
    test_convertYEARC();
    test_convertYEARD();
    test_convertYEARE();
    return 0;
}